In [1]:
import pandas as pd
import numpy as np
import time

import re

# 데이터 전처리

In [2]:
data = pd.read_csv('pretty_beer_preprocessing.csv', encoding='utf-8', index_col=0)

In [3]:
data

,ID,beer_name,date,grade,Aroma,Appearance,Flavor,Mouthfeel,Overall,beer_review
0,"italianjohn(5,276)",Kloud Original Gravity,"September 6, 2021",2.8,5.0,3.0,5.0,3.0,12.0,Clear golden blonde pour with a thin white hea...
1,orda(284),Kloud Original Gravity,"August 29, 2021",3.9,10.0,5.0,10.0,5.0,9.0,Appearance: golden amber; slight head\nTaste: ...
2,"Radek Kliber(8,065)",Kloud Original Gravity,"June 5, 2021",2.4,6.0,3.0,4.0,2.0,9.0,"Bottle 330 ml \n\nAroma: nice, fresh, on dry s..."
3,"geologyguy(2,575)",Kloud Original Gravity,"May 26, 2021",2.3,4.0,3.0,4.0,3.0,9.0,Smell is light of malt...taste is a that malt ...
4,Wolff90(203),Kloud Original Gravity,"February 16, 2021",1.0,1.0,1.0,1.0,1.0,6.0,Rating copied from Untappd. Had while flying A...
...,...,...,...,...,...,...,...,...,...,...
83186,bourne(161),Cafri,"March 21, 2006",1.3,2.0,2.0,3.0,2.0,4.0,I didnt think this was beer when I bought it. ...
83187,curvedbeer(11),Cafri,"November 6, 2005",1.0,2.0,3.0,1.0,1.0,3.0,Of all of the commercially brewed beers I’ve t...
83188,"tomciccateri(1,033)",Cafri,"September 5, 2007",2.2,3.0,3.0,4.0,2.0,10.0,"From a can onboard a KAL flight. 4.2%, with no..."
83189,"Papsoe(25,039)",Cafri,"June 13, 2005",2.1,5.0,2.0,4.0,2.0,8.0,(Bottle 48 cl) Again - for Korea - this beauti...
83190,"MrRomero(1,976)",Cafri,"March 21, 2004",1.7,3.0,2.0,3.0,2.0,7.0,Probably my favorite Korean beer but not as av...

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 81853 entries, 0 to 83190
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           81853 non-null  object
 1   beer_name    81853 non-null  object
 2   date         81852 non-null  object
 3   grade        81853 non-null  float64
 4   Aroma        81853 non-null  float64
 5   Appearance   81853 non-null  float64
 6   Flavor       81853 non-null  float64
 7   Mouthfeel    81853 non-null  float64
 8   Overall      81853 non-null  float64
 9   beer_review  81853 non-null  object
dtypes: float64(6), object(4)
memory usage: 6.9+ MB

In [5]:
tmp = data.copy()

In [64]:
tmp

,ID,beer_name,date,grade,Aroma,Appearance,Flavor,Mouthfeel,Overall,beer_review
0,"italianjohn(5,276)",Kloud Original Gravity,"September 6, 2021",2.8,5.0,3.0,5.0,3.0,12.0,Clear golden blonde pour with a thin white hea...
1,orda(284),Kloud Original Gravity,"August 29, 2021",3.9,10.0,5.0,10.0,5.0,9.0,Appearance: golden amber; slight head\nTaste: ...
2,"Radek Kliber(8,065)",Kloud Original Gravity,"June 5, 2021",2.4,6.0,3.0,4.0,2.0,9.0,"Bottle 330 ml \n\nAroma: nice, fresh, on dry s..."
3,"geologyguy(2,575)",Kloud Original Gravity,"May 26, 2021",2.3,4.0,3.0,4.0,3.0,9.0,Smell is light of malt...taste is a that malt ...
4,Wolff90(203),Kloud Original Gravity,"February 16, 2021",1.0,1.0,1.0,1.0,1.0,6.0,Rating copied from Untappd. Had while flying A...
...,...,...,...,...,...,...,...,...,...,...
83186,bourne(161),Cafri,"March 21, 2006",1.3,2.0,2.0,3.0,2.0,4.0,I didnt think this was beer when I bought it. ...
83187,curvedbeer(11),Cafri,"November 6, 2005",1.0,2.0,3.0,1.0,1.0,3.0,Of all of the commercially brewed beers I’ve t...
83188,"tomciccateri(1,033)",Cafri,"September 5, 2007",2.2,3.0,3.0,4.0,2.0,10.0,"From a can onboard a KAL flight. 4.2%, with no..."
83189,"Papsoe(25,039)",Cafri,"June 13, 2005",2.1,5.0,2.0,4.0,2.0,8.0,(Bottle 48 cl) Again - for Korea - this beauti...
83190,"MrRomero(1,976)",Cafri,"March 21, 2004",1.7,3.0,2.0,3.0,2.0,7.0,Probably my favorite Korean beer but not as av...

In [24]:
tmp['ID'] = tmp['ID'].apply(lambda x:x[:x.find('(')])

In [32]:
tmp

,ID,beer_name,date,grade,Aroma,Appearance,Flavor,Mouthfeel,Overall,beer_review
0,italianjohn,Kloud Original Gravity,"September 6, 2021",2.8,5.0,3.0,5.0,3.0,12.0,Clear golden blonde pour with a thin white hea...
1,orda,Kloud Original Gravity,"August 29, 2021",3.9,10.0,5.0,10.0,5.0,9.0,Appearance: golden amber; slight head\nTaste: ...
2,Radek Kliber,Kloud Original Gravity,"June 5, 2021",2.4,6.0,3.0,4.0,2.0,9.0,"Bottle 330 ml \n\nAroma: nice, fresh, on dry s..."
3,geologyguy,Kloud Original Gravity,"May 26, 2021",2.3,4.0,3.0,4.0,3.0,9.0,Smell is light of malt...taste is a that malt ...
4,Wolff90,Kloud Original Gravity,"February 16, 2021",1.0,1.0,1.0,1.0,1.0,6.0,Rating copied from Untappd. Had while flying A...
...,...,...,...,...,...,...,...,...,...,...
83186,bourne,Cafri,"March 21, 2006",1.3,2.0,2.0,3.0,2.0,4.0,I didnt think this was beer when I bought it. ...
83187,curvedbeer,Cafri,"November 6, 2005",1.0,2.0,3.0,1.0,1.0,3.0,Of all of the commercially brewed beers I’ve t...
83188,tomciccateri,Cafri,"September 5, 2007",2.2,3.0,3.0,4.0,2.0,10.0,"From a can onboard a KAL flight. 4.2%, with no..."
83189,Papsoe,Cafri,"June 13, 2005",2.1,5.0,2.0,4.0,2.0,8.0,(Bottle 48 cl) Again - for Korea - this beauti...
83190,MrRomero,Cafri,"March 21, 2004",1.7,3.0,2.0,3.0,2.0,7.0,Probably my favorite Korean beer but not as av...

In [26]:
# 필요없는 칼럼 삭제
a = tmp.drop(['date','Aroma', 'Appearance', 'Flavor', 'Mouthfeel', 'Overall', 'beer_review'], axis = 1)
a

                 ID               beer_name  grade
0       italianjohn  Kloud Original Gravity    2.8
1              orda  Kloud Original Gravity    3.9
2      Radek Kliber  Kloud Original Gravity    2.4
3        geologyguy  Kloud Original Gravity    2.3
4           Wolff90  Kloud Original Gravity    1.0
...             ...                     ...    ...
83186        bourne                   Cafri    1.3
83187    curvedbeer                   Cafri    1.0
83188  tomciccateri                   Cafri    2.2
83189        Papsoe                   Cafri    2.1
83190      MrRomero                   Cafri    1.7

[81853 rows x 3 columns]

In [27]:
b = tmp.drop(['date','Aroma', 'Appearance', 'Flavor', 'Mouthfeel', 'Overall', 'beer_review'], axis = 1)
b

                 ID               beer_name  grade
0       italianjohn  Kloud Original Gravity    2.8
1              orda  Kloud Original Gravity    3.9
2      Radek Kliber  Kloud Original Gravity    2.4
3        geologyguy  Kloud Original Gravity    2.3
4           Wolff90  Kloud Original Gravity    1.0
...             ...                     ...    ...
83186        bourne                   Cafri    1.3
83187    curvedbeer                   Cafri    1.0
83188  tomciccateri                   Cafri    2.2
83189        Papsoe                   Cafri    2.1
83190      MrRomero                   Cafri    1.7

[81853 rows x 3 columns]

In [28]:
# beer_name - ID 피벗테이블 생성
table1 = a.pivot_table(a, index = 'beer_name', columns = 'ID')

In [29]:
# ID - beer_name 피벗테이블 생성
table2 = b.pivot_table(b, index = 'ID', columns = 'beer_name')

In [67]:
# # 피벗테이블 생성

# # beer_name - ID 피벗테이블
# table1 = a.pivot_table(a, index = ['beer_name'], columns = ['ID'])

# # ID - beer_name 피벗테이블
# table2 = b.pivot_table(b, index = ['ID'], columns = ['beer_name'])

In [30]:
table1.head()

                       grade                                                   \
ID                             0. 007lund 00cobraR 09maso3 0o9i 100Beier 1010
beer_name
0.0                      NaN  0.0     NaN      NaN     NaN  NaN      NaN  NaN
7Bräu Gompyo Wheatbeer   NaN  NaN     NaN      NaN     NaN  NaN      NaN  NaN
ARK Seoulite Ale         NaN  NaN     NaN      NaN     NaN  NaN      NaN  NaN
Asahi Super Dry          NaN  NaN     NaN      NaN     NaN  NaN      NaN  2.4
Asahi Super Dry Black    NaN  NaN     NaN      NaN     NaN  NaN      NaN  NaN

                                   ...                                    \
ID                     1040 11026  ... zpeyote zscsintalan ztrvz zuminuk
beer_name                          ...
0.0                     NaN   NaN  ...     NaN         NaN   NaN     NaN
7Bräu Gompyo Wheatbeer  NaN   NaN  ...     NaN         NaN   NaN     NaN
ARK Seoulite Ale        NaN   NaN  ...     NaN         NaN   NaN     NaN
Asahi Super Dry         NaN   NaN  ...     NaN         NaN   NaN     NaN
Asahi Super Dry Black   NaN   NaN  ...     NaN         NaN   NaN     NaN


ID                     zvikar zvsn zxxzooz zygell zygomatic99 zyster99
beer_name
0.0                       NaN  NaN     NaN    NaN         NaN      NaN
7Bräu Gompyo Wheatbeer    NaN  NaN     NaN    NaN         NaN      NaN
ARK Seoulite Ale          NaN  NaN     NaN    NaN         NaN      NaN
Asahi Super Dry           1.2  NaN     NaN    2.7         NaN      NaN
Asahi Super Dry Black     2.5  NaN     NaN    NaN         NaN      NaN

[5 rows x 15512 columns]

In [31]:
table2.head()

          grade                                                          \
beer_name   0.0 7Bräu Gompyo Wheatbeer ARK Seoulite Ale Asahi Super Dry
ID
            NaN                    NaN              NaN             NaN
0.          0.0                    NaN              NaN             NaN
007lund     NaN                    NaN              NaN             NaN
00cobraR    NaN                    NaN              NaN             NaN
09maso3     NaN                    NaN              NaN             NaN

                                                        \
beer_name Asahi Super Dry Black Bavaria 8.6 (Original)
ID
                            NaN                    NaN
0.                          NaN                    NaN
007lund                     NaN                    NaN
00cobraR                    NaN                    NaN
09maso3                     NaN                    NaN

                                                  \
beer_name Bavaria Pilsener / Premium Beer Beck's
ID
                                      NaN    NaN
0.                                    NaN    NaN
007lund                               NaN    2.6
00cobraR                              NaN    2.3
09maso3                               NaN    NaN

                                                                      ...  \
beer_name Berliner Kindl Jubiläums Pilsener Premium Bintang Pilsener  ...
ID                                                                    ...
                                                NaN              NaN  ...
0.                                              NaN              NaN  ...
007lund                                         NaN              NaN  ...
00cobraR                                        NaN              NaN  ...
09maso3                                         NaN              NaN  ...

                                                                           \
beer_name Stephans Bräu Premium Pilsener Suntory The Premium Malt's Terra
ID
                                     NaN                        NaN   NaN
0.                                   NaN                        NaN   NaN
007lund                              NaN                        NaN   NaN
00cobraR                             NaN                        NaN   NaN
09maso3                              NaN                        NaN   NaN

                                                                      \
beer_name Tiger Beer Tiger Radler Lemon Tsingtao Tsingtao Wheat Beer
ID
                 NaN                NaN      NaN                 NaN
0.               NaN                NaN      NaN                 NaN
007lund          NaN                NaN      2.5                 NaN
00cobraR         NaN                NaN      2.1                 NaN
09maso3          NaN                NaN      NaN                 NaN

                                                                 \
beer_name Victoria Bitter Volfas Engelman Grünberger Hefeweizen
ID
                      NaN                                   NaN
0.                    NaN                                   NaN
007lund               NaN                                   NaN
00cobraR              NaN                                   NaN
09maso3               NaN                                   NaN


beer_name Warsteiner Premium Verum
ID
                               NaN
0.                             NaN
007lund                        4.1
00cobraR                       NaN
09maso3                        2.7

[5 rows x 88 columns]

## 인덱스가 beer_name 인걸로 사용
beer_name - ID 피벗테이블
table1 = a.pivot_table(a, index = ['beer_name'], columns = ['ID'])

In [33]:
# 아이템기반 협업 필터링을 위해 인덱스가 beer_name 인걸로 사용

# 피벗테이블 NaN처리
table1.fillna(0,inplace=True)
table1.head()

                       grade                                                   \
ID                             0. 007lund 00cobraR 09maso3 0o9i 100Beier 1010
beer_name
0.0                      0.0  0.0     0.0      0.0     0.0  0.0      0.0  0.0
7Bräu Gompyo Wheatbeer   0.0  0.0     0.0      0.0     0.0  0.0      0.0  0.0
ARK Seoulite Ale         0.0  0.0     0.0      0.0     0.0  0.0      0.0  0.0
Asahi Super Dry          0.0  0.0     0.0      0.0     0.0  0.0      0.0  2.4
Asahi Super Dry Black    0.0  0.0     0.0      0.0     0.0  0.0      0.0  0.0

                                   ...                                    \
ID                     1040 11026  ... zpeyote zscsintalan ztrvz zuminuk
beer_name                          ...
0.0                     0.0   0.0  ...     0.0         0.0   0.0     0.0
7Bräu Gompyo Wheatbeer  0.0   0.0  ...     0.0         0.0   0.0     0.0
ARK Seoulite Ale        0.0   0.0  ...     0.0         0.0   0.0     0.0
Asahi Super Dry         0.0   0.0  ...     0.0         0.0   0.0     0.0
Asahi Super Dry Black   0.0   0.0  ...     0.0         0.0   0.0     0.0


ID                     zvikar zvsn zxxzooz zygell zygomatic99 zyster99
beer_name
0.0                       0.0  0.0     0.0    0.0         0.0      0.0
7Bräu Gompyo Wheatbeer    0.0  0.0     0.0    0.0         0.0      0.0
ARK Seoulite Ale          0.0  0.0     0.0    0.0         0.0      0.0
Asahi Super Dry           1.2  0.0     0.0    2.7         0.0      0.0
Asahi Super Dry Black     2.5  0.0     0.0    0.0         0.0      0.0

[5 rows x 15512 columns]

# 아이템기반 협업 필터링

## 유사한 아이템끼리 추천을 해주는 방식 
평점이 비슷한 맥주를 추천해 주는 것

코사인 유사도 값을 이용하여 유사도 계산

In [34]:
# 유사도값 추출 (코사인 유사도)

from sklearn.metrics.pairwise import cosine_similarity

similarity_rate = cosine_similarity(table1, table1)
print(similarity_rate)

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.31238139 ... 0.03708988 0.         0.02095593]
 [0.         0.31238139 1.         ... 0.06273333 0.         0.04164764]
 ...
 [0.         0.03708988 0.06273333 ... 1.         0.0298855  0.23866206]
 [0.         0.         0.         ... 0.0298855  1.         0.05988322]
 [0.         0.02095593 0.04164764 ... 0.23866206 0.05988322 1.        ]]

In [35]:
# 유사도값을 가진 데이터프레임 새성
simlarity_rate_df = pd.DataFrame(
    data = similarity_rate,
    index = table1.index,
    columns = table1.index)

In [36]:
simlarity_rate_df.head()

beer_name,0.0,7Bräu Gompyo Wheatbeer,ARK Seoulite Ale,Asahi Super Dry,Asahi Super Dry Black,Bavaria 8.6 (Original),Bavaria Pilsener / Premium Beer,Beck's,Berliner Kindl Jubiläums Pilsener Premium,Bintang Pilsener,...,Stephans Bräu Premium Pilsener,Suntory The Premium Malt's,Terra,Tiger Beer,Tiger Radler Lemon,Tsingtao,Tsingtao Wheat Beer,Victoria Bitter,Volfas Engelman Grünberger Hefeweizen,Warsteiner Premium Verum
beer_name,,,,,,,,,,,,,,,,,,,,,
0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7Bräu Gompyo Wheatbeer,0.0,1.000000,0.312381,0.029136,0.091327,0.000000,0.000000,0.000000,0.000000,0.046045,...,0.000000,0.084268,0.146818,0.028792,0.268753,0.017540,0.000000,0.037090,0.000000,0.020956
ARK Seoulite Ale,0.0,0.312381,1.000000,0.048865,0.050718,0.021124,0.028318,0.033723,0.064630,0.078839,...,0.030779,0.115683,0.116951,0.046459,0.118779,0.041430,0.170319,0.062733,0.000000,0.041648
Asahi Super Dry,0.0,0.029136,0.048865,1.000000,0.183970,0.251744,0.361223,0.420413,0.220366,0.311490,...,0.110734,0.218082,0.084009,0.463016,0.074244,0.467081,0.088130,0.272735,0.041949,0.413144
Asahi Super Dry Black,0.0,0.091327,0.050718,0.183970,1.000000,0.094113,0.123946,0.122799,0.095853,0.170874,...,0.044972,0.345819,0.065994,0.164266,0.137974,0.118205,0.059078,0.158418,0.054537,0.122163

In [37]:
simlarity_rate_df.drop(['0.0'], axis = 0)

beer_name,0.0,7Bräu Gompyo Wheatbeer,ARK Seoulite Ale,Asahi Super Dry,Asahi Super Dry Black,Bavaria 8.6 (Original),Bavaria Pilsener / Premium Beer,Beck's,Berliner Kindl Jubiläums Pilsener Premium,Bintang Pilsener,...,Stephans Bräu Premium Pilsener,Suntory The Premium Malt's,Terra,Tiger Beer,Tiger Radler Lemon,Tsingtao,Tsingtao Wheat Beer,Victoria Bitter,Volfas Engelman Grünberger Hefeweizen,Warsteiner Premium Verum
beer_name,,,,,,,,,,,,,,,,,,,,,
7Bräu Gompyo Wheatbeer,0.0,1.000000,0.312381,0.029136,0.091327,0.000000,0.000000,0.000000,0.000000,0.046045,...,0.000000,0.084268,0.146818,0.028792,0.268753,0.017540,0.000000,0.037090,0.000000,0.020956
ARK Seoulite Ale,0.0,0.312381,1.000000,0.048865,0.050718,0.021124,0.028318,0.033723,0.064630,0.078839,...,0.030779,0.115683,0.116951,0.046459,0.118779,0.041430,0.170319,0.062733,0.000000,0.041648
Asahi Super Dry,0.0,0.029136,0.048865,1.000000,0.183970,0.251744,0.361223,0.420413,0.220366,0.311490,...,0.110734,0.218082,0.084009,0.463016,0.074244,0.467081,0.088130,0.272735,0.041949,0.413144
Asahi Super Dry Black,0.0,0.091327,0.050718,0.183970,1.000000,0.094113,0.123946,0.122799,0.095853,0.170874,...,0.044972,0.345819,0.065994,0.164266,0.137974,0.118205,0.059078,0.158418,0.054537,0.122163
Bavaria 8.6 (Original),0.0,0.000000,0.021124,0.251744,0.094113,1.000000,0.330498,0.230330,0.205613,0.245079,...,0.158736,0.084041,0.024121,0.253183,0.077289,0.236044,0.074087,0.199545,0.056064,0.243123
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Tsingtao,0.0,0.017540,0.041430,0.467081,0.118205,0.236044,0.358426,0.441169,0.204520,0.318589,...,0.096926,0.171181,0.090634,0.474249,0.073824,1.000000,0.066540,0.263831,0.055143,0.448028
Tsingtao Wheat Beer,0.0,0.000000,0.170319,0.088130,0.059078,0.074087,0.081155,0.073138,0.134990,0.075390,...,0.000000,0.061878,0.052406,0.072050,0.037003,0.066540,1.000000,0.050077,0.151680,0.054371
Victoria Bitter,0.0,0.037090,0.062733,0.272735,0.158418,0.199545,0.261532,0.261665,0.218941,0.323757,...,0.066941,0.190554,0.092257,0.322760,0.078572,0.263831,0.050077,1.000000,0.029886,0.238662
Volfas Engelman Grünberger Hefeweizen,0.0,0.000000,0.000000,0.041949,0.054537,0.056064,0.083751,0.065537,0.143981,0.021758,...,0.124611,0.014136,0.000000,0.053302,0.000000,0.055143,0.151680,0.029886,1.000000,0.059883
Warsteiner Premium Verum,0.0,0.020956,0.041648,0.413144,0.122163,0.243123,0.378492,0.488707,0.225129,0.274443,...,0.100344,0.155076,0.077884,0.425216,0.048846,0.448028,0.054371,0.238662,0.059883,1.000000

# 맥주추천 사용자 함수 생성
사용자가 어떤 맥주를 선택하였을 때(매개변수로 맥주이름 입력)

비슷한 맥주를 추천

In [38]:
# 가장 유사도가 높은 top5
def recommand_beer(beer_name) : 
    return simlarity_rate_df[beer_name].sort_values(ascending=False)[:6]
recommand_beer("Tiger Beer")

beer_name
Tiger Beer               1.000000
Tsingtao                 0.474249
Asahi Super Dry          0.463016
Peroni Nastro Azzurro    0.451297
Erdinger Weissbier       0.435578
Kirin Ichiban            0.435102
Name: Tiger Beer, dtype: float64